spring.application.name=Shifter

# Database Configuration AWS
spring.datasource.url=jdbc:mysql://shifter.c55gvcjanov4.ca-west-1.rds.amazonaws.com:3306/shifter
spring.datasource.username=admin
spring.datasource.password=shifter1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# LOCAL DATABASE
#spring.datasource.url=jdbc:mysql://localhost:3306/shifter?serverTimezone=UTC&createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=laarn1@*
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#server.port=8081  //double entry


# JWT Configuration
jwt.secret=your-very-long-secret-key-that-is-at-least-64-characters-for-HS512-algorithm-needs-to-be-this-long

# 15 minutes in milliseconds
jwt.expiration=7200000 

# Server Configuration
server.port=8081
server.servlet.context-path=/

# Swagger UI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.filter=true


# Logging for debugging
logging.level.org.springdoc=DEBUG

server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-binding-errors=always
server.error.include-exception=true

# =======================
# CORS Configuration - for Frontend Integration
# =======================
cors.allowed-origins=http://localhost:3000
cors.allowed-methods=GET,POST,PUT,DELETE
cors.allowed-headers=*
cors.allow-credentials=true
